apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: registry.ng.bluemix.net/flask-node/app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
